type TypeCode{
  code: ID!
  name: String
}

type InformationProdivder{
  gln: String!
}

type Allergen {
  typeCode: TypeCode!
  containmentCode: TypeCode!
}

type IngredientInformation{
  ingredientStatement: String
}

type AllergenInformation {
  allergens: [Allergen!]
  statement: String
}

type HealthRelated{
   freeFromCodes: TypeCode
}

type ProductIdentifier{
  externalId: String!
  targetMarket: TypeCode!
}

type IncomingImageProduct {
  productIdentifier: ProductIdentifier!
  informationProvider: InformationProdivder!
  id: ID!
  name: String!
}


type IncomingIngredientProduct {
  id: ID!
  ingredientInformation: IngredientInformation
  allergenInformation: AllergenInformation
  modifiedDateAndTime: Date!
  sourceLastChangedDateAndTime: Date
}


