type TypeCode{
  code: ID!
}

type InformationProdivder{
  gln: String!
}

type ProductIdentifier{
  externalId: String!
  targetMarket: TypeCode!
}

type IncomingImageProduct {
  productIdentifier: ProductIdentifier!
  informationProvider: InformationProdivder!
  id: ID!
}
